# --- Profil DEV : PostgreSQL local (Docker) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/tontinesafe
spring.datasource.username=tontinesafe
spring.datasource.password=tontinesafe
spring.jpa.show-sql=true
