# --- Profil DEV : PostgreSQL local (Docker) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/tontyn
spring.datasource.username=tontyn
spring.datasource.password=tontyn
spring.jpa.show-sql=true
